[versions]
kotlin = "2.2.0"
ksp = "2.3.3" # https://github.com/google/ksp/releases
dokka = "2.0.0"
jsoup = "1.18.1" # https://github.com/jhy/jsoup/releases
mavenPublish = "0.29.0" # https://github.com/vanniktech/gradle-maven-publish-plugin/releases
assertk = "0.28.0"  # https://github.com/willowtreeapps/assertk/releases
cache4k = "0.13.0"  # https://github.com/ReactiveCircus/cache4k/releases
testResources = "0.4.0"
kotlinx-coroutines = "1.7.3"  # https://github.com/kotlin/kotlinx.coroutines/releases
okhttp = "5.3.2" # https://square.github.io/okhttp/changelogs/changelog
testParameterInjector = "1.8"
clikt = "3.5.2"
mordant = "2.0.0-beta13"
junit = "4.13.2"
moshi = "1.15.0"
poko = "0.19.3" # https://github.com/drewhamilton/Poko/releases
metalava = "0.4.0-alpha03" # https://github.com/tylerbwong/metalava-gradle/releases
bytesize = "2.1.0" # https://github.com/saket/byte-size/releases

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
mavenPublish = { id = "com.vanniktech.maven.publish", version.ref = "mavenPublish" }
testResources = { id = "com.goncalossilva.resources", version.ref = "testResources" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
poko = { id = "dev.drewhamilton.poko", version.ref = "poko" }
metalava = { id = "me.tylerbwong.gradle.metalava", version.ref = "metalava" }

[libraries]
junit = { module = "junit:junit", version.ref = "junit" }
jsoup = { module = "org.jsoup:jsoup", version.ref = "jsoup" }
okhttp-core = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp" }
okhttp-mockWebServer = { module = "com.squareup.okhttp3:mockwebserver", version.ref = "okhttp" }
okhttp-coroutines = { module = "com.squareup.okhttp3:okhttp-coroutines", version.ref = "okhttp" }
assertk = { module = "com.willowtreeapps.assertk:assertk", version.ref = "assertk" }
cache4k = { module = "io.github.reactivecircus.cache4k:cache4k", version.ref = "cache4k" }
testResources = { module = "com.goncalossilva:resources", version.ref = "testResources" }
testParameterInjector = { module = "com.google.testparameterinjector:test-parameter-injector", version.ref = "testParameterInjector" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
clikt = { module = "com.github.ajalt.clikt:clikt", version.ref = "clikt" }
mordant = { module = "com.github.ajalt.mordant:mordant", version.ref = "mordant" }
moshi-core = { module = "com.squareup.moshi:moshi", version.ref = "moshi" }
moshi-codegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "moshi" }
bytesize = { module = "me.saket.bytesize:bytesize", version.ref = "bytesize" }
